"""Add rolle to Benutzer

Revision ID: 182868a135cd
Revises: bcc62cac9e76
Create Date: 2025-04-13 21:10:29.599638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182868a135cd'
down_revision = 'bcc62cac9e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rolle', sa.String(length=20), nullable=False))

    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.alter_column('benutzer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.alter_column('benutzer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.drop_column('rolle')

    # ### end Alembic commands ###
