"""Add bilder_einpackfertig

Revision ID: 4ee64a77c928
Revises: 6c6ac4551e4b
Create Date: 2025-05-28 15:20:46.930979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee64a77c928'
down_revision = '6c6ac4551e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bilder_fertig', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.drop_column('bilder_fertig')

    # ### end Alembic commands ###
