"""add einpackbereit flag

Revision ID: 6c6ac4551e4b
Revises: 8f0cb67a7964
Create Date: 2025-05-28 15:11:29.154753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6ac4551e4b'
down_revision = '8f0cb67a7964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('einpackbereit', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.drop_column('einpackbereit')

    # ### end Alembic commands ###
