"""Hersteller-FK zu Modell hinzugefügt

Revision ID: 85262fe58ba8
Revises: bcc62cac9e76
Create Date: 2025-04-21 21:16:29.213297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85262fe58ba8'
down_revision = 'bcc62cac9e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hersteller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.alter_column('benutzer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('modell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hersteller_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'hersteller', ['hersteller_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modell', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hersteller_id')

    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.alter_column('benutzer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('hersteller')
    # ### end Alembic commands ###
