"""Add GeraetBild table

Revision ID: 8f0cb67a7964
Revises: bfc4f064175c
Create Date: 2025-05-28 14:22:12.992098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f0cb67a7964'
down_revision = 'bfc4f064175c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geraet_bild',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geraet_id', sa.Integer(), nullable=False),
    sa.Column('pfad', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['geraet_id'], ['geraete.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geraet_bild')
    # ### end Alembic commands ###
