"""Add ausgepacktplus

Revision ID: b0f806e35022
Revises: dbdc7cff453c
Create Date: 2025-05-28 16:01:53.654613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f806e35022'
down_revision = 'dbdc7cff453c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ausgepackt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gereinigt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('getestet', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.drop_column('getestet')
        batch_op.drop_column('gereinigt')
        batch_op.drop_column('ausgepackt')

    # ### end Alembic commands ###
