"""Add benutzer_id to Geraet

Revision ID: bcc62cac9e76
Revises: 
Create Date: 2025-04-09 06:32:10.312469
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc62cac9e76'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Entferne die Zeilen zum Löschen der Tabelle 'modelle'
    # op.drop_table('modelle')

    # Jetzt die benutzer_id hinzufügen und den Foreign Key korrekt erstellen
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        # Hinzufügen der Spalte 'benutzer_id' für die Beziehung
        batch_op.add_column(sa.Column('benutzer_id', sa.Integer(), nullable=False))
        
        # Hier den Foreign Key Constraint richtig erstellen:
        batch_op.create_foreign_key(
            constraint_name='fk_geraete_benutzer',  # Name des Constraints
            source_table='geraete',                 # Quelltabelle (Geraet)
            referent_table='benutzer',              # Referenztabelle (Benutzer)
            local_cols=['benutzer_id'],             # Die Spalte in der Quelltabelle (Geraet)
            remote_cols=['id']                     # Die Referenzspalte in der Referenztabelle (Benutzer)
        )

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.drop_constraint('fk_geraete_benutzer', type_='foreignkey')
        batch_op.drop_column('benutzer_id')

    # ### end Alembic commands ###

