"""add ukat to modell

Revision ID: bfc4f064175c
Revises: 85262fe58ba8
Create Date: 2025-05-28 13:30:18.862079
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bfc4f064175c'
down_revision = '85262fe58ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modell', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unterkategorie_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_modell_unterkategorie',  # 🧠 Name hinzugefügt
            'unterkategorie',
            ['unterkategorie_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modell', schema=None) as batch_op:
        batch_op.drop_constraint('fk_modell_unterkategorie', type_='foreignkey')
        batch_op.drop_column('unterkategorie_id')

    op.create_table(
        '_alembic_tmp_geraete',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('qrcode', sa.VARCHAR(), nullable=False),
        sa.Column('modell_id', sa.INTEGER(), nullable=False),
        sa.Column('zustand_id', sa.INTEGER(), nullable=False),
        sa.Column('benutzer_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], name='fk_geraete_benutzer'),
        sa.ForeignKeyConstraint(['modell_id'], ['modell.id']),
        sa.ForeignKeyConstraint(['zustand_id'], ['zustaende.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('qrcode')
    )
    # ### end Alembic commands ###

