"""Usermodell erweitert

Revision ID: d60eaf0fb785
Revises: 794a30e8f9a3
Create Date: 2025-05-29 17:12:07.557206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60eaf0fb785'
down_revision = '794a30e8f9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('aktiv', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('gesperrt', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('gesperrt')
        batch_op.drop_column('aktiv')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
