"""Add bilder_fertig

Revision ID: dbdc7cff453c
Revises: 4ee64a77c928
Create Date: 2025-05-28 15:23:13.918925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdc7cff453c'
down_revision = '4ee64a77c928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bilder_einpackfertig', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geraete', schema=None) as batch_op:
        batch_op.drop_column('bilder_einpackfertig')

    # ### end Alembic commands ###
